name: cv-resume
recipe: wordpress
proxy:
  appserver: # This could be anything you like as long as you point the domain to 127.0.0.1 in your /etc/hosts file
    - cv-resume.lndo.site
  pma: # Use the below url to access PHPMyAdmin :-)
    - pma.cv-resume.lndo.site
  mailhog: # Use mail url for a way to view emails send from your local dev instance
    - mail.cv-resume.lndo.site
config:
  env: dev
  php: '7.3'
  via: apache
  webroot: public_html
  database: mariadb
  xdebug: true